# -*- mode: ruby -*-
# vi: set ft=ruby :

VM_BOX = ENV["VM_BOX"] || "peru/windows-10-enterprise-x64-eval"
VM_RAM = ENV["VM_RAM"] || "1024"
VM_CPU = ENV["VM_CPU"] || "2"

#N = ENV["N"].to_i || 3
N = 3

Vagrant.configure("2") do |config|

  config.vm.box = VM_BOX
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "libvirt" do |lv|
    lv.memory = VM_RAM
    lv.cpus = VM_CPU
  end
  config.vm.provider "virtualbox" do |vb|
    vb.memory = VM_RAM
    vb.cpus = VM_CPU
  end

  (1..N).each do |a|
    config.vm.define "windows-#{a}" do |vm|
      vm.vm.hostname = "windows"
      vm.vm.network "private_network", ip: "192.168.121.18#{a}"
    end
  end

end
