---
#- name: Remove old Admin
#  win_user:
#    name: "{{ old_admin }}"
#    state: absent

- name: Rename and Activate the default Administrator (Powershell)
  win_shell: |
    $old_admin = "{{ old_admin }}"
    $new_admin = "{{ new_admin }}"
    $new_admin_pwd = "{{ new_admin_pwd }}"

    if ( Get-LocalUser $old_admin )
    {
      Rename-LocalUser -Name $old_admin -NewName $new_admin
      Enable-LocalUser -Name $new_admin
      Set-LocalUser -Name $new_admin -Password ( ConvertTo-SecureString $new_admin_pwd -AsPlainText -Force ) -PasswordNeverExpires $true
    } else { exit }
