---
- hosts: all
  vars:
    old_admin: Administrator

  tasks:

#  - name: Remove old Admin
#    win_user:
#      name: "{{ old_admin }}"
#      state: absent

#  - name: Remove old Admin (Powershell)
#    win_shell: TODO
