---
- hosts: all
  vars:
    admin: my-admin
    admin_pwd: password
    user: my-user
    new_user: new-user

  tasks:

  - name: Create new Admin
    win_user:
      name: "{{ admin }}"
      password: "{{ admin_pwd }}"
      state: present
      groups:
      - Users
      - Administrators

  - name: Create User
    win_user:
      name: "{{ user }}"
      state: present
      groups:
      - Users

  - name: Create Additional User
    win_user:
      name: "{{ new_user }}"
      state: present
      groups:
      - Users
