---
- hosts: all
  vars:
    hostname: a-beautiful-hostname
    admin: my-admin
    admin_pwd: password
    user: my-user
    new_user: new-user
    old_admin: Administrator

  tasks:

  - name: Change Hostname
    win_hostname:
      name: "{{ hostname }}"

  - name: Create new Admin
    win_user:
      name: "{{ admin }}"
      password: "{{ admin_pwd }}"
      state: present
      groups:
      - Users
      - Administrators

  - name: Create User
    win_user:
      name: "{{ user }}"
      state: present
      groups:
      - Users

  - name: Create Additional User
    win_user:
      name: "{{ new_user }}"
      state: present
      groups:
      - Users
    old_admin: Administrator

  - name: Remove old Admin
    win_user:
      name: "{{ old_admin }}"
      state: absent

  - name: Change Keyboard-Layout to "de-DE"
    win_shell: Set-WinUserLanguageList -LanguageList de-DE -Force
    #become_user: System

  - name: Install Windows Updates and Reboot if needed
    win_updates:
      category_names:
      - CriticalUpdates
      - SecurityUpdates
      - UpdatesRollups
      reboot: yes

  - name: Install Base Software
    win_chocolatey:
      name:
      - firefox
      - 7zip
      - thunderbird
      - nextcloud-client
      state: present

  - name: Install Additional Software
    win_chocolatey:
      name:
      - office-tool
      - chromium
      - zoom
      #- webex-meetings
      state: present

  - name: Office-2019 - Copy Standard Configuration XML
    win_copy:
      src: ./configuration_standard.xml
      dest: 'C:\Users\vagrant\AppData\Local\office-tool\Office Tool\files\'

#  - name: Office-2019 - Install Standard Version
#    win_shell: .\setup.exe /configure .\configuration_standard.xml
#    args:
#      chdir: 'C:\Users\vagrant\AppData\Local\office-tool\Office Tool\files'
